[api_keys]
google_api_key = "AIzaSyCo8ciO8_1MuD-gb4jgeg1RhKbj1zLYtmI"

[pipedream_urls]
youtube = "https://mcp.pipedream.net/7c74e408-2fed-4cc5-9ed0-49be40ee4d2b/youtube_data_api"
drive = "https://mcp.pipedream.net/7c74e408-2fed-4cc5-9ed0-49be40ee4d2b/google_drive"
notion = "https://mcp.pipedream.net/7c74e408-2fed-4cc5-9ed0-49be40ee4d2b/notion"
